### ISSUE TITLE
Headings look like text

### ISSUE THREAD

**Issue by ConventoAngelo** [notion-enhancer/desktop#668]
I tried using headings and it looks like small text. This happens for all types of headings, e.g. Headings 1, Headings 2, and Headings 3.
![image](https://user-images.githubusercontent.com/66541188/146179580-06e9f98a-a9c2-4900-8949-a0bb9440f6c9.png)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/667

**Comment by ConventoAngelo** [comment]
![image](https://user-images.githubusercontent.com/66541188/146179683-aec1221b-7572-493a-bfcd-1b289a2029b5.png)
This is how it looks like compared to regular text.

**Comment by dragonwocky** [comment]
a fix will be out with v0.11.0, until then everyone's just gonna have to wait. I'm getting it done as fast as I reasonably can.

**Comment by tibitTW** [comment]
For those still waiting for `v.0.11.0`, you can use **custom inserts** and import the css code below:

```css
[placeholder='Heading 1'] {
    font-size: 2em !important;
}
[placeholder='Heading 2'] {
    font-size: 1.5em !important;
}
[placeholder='Heading 3'] {
    font-size: 1.2em !important;
}

```

It can temporary solve this issue.
