### ISSUE TITLE
The Inline Code Black 's bg color

### ISSUE THREAD

**Issue by l782993610** [notion-enhancer/desktop#698]
inline code block with custom color doesn't change it's bg color although the variable '--theme--code_inline' is defined.

**Comment by l782993610** [comment]
I modify the theme.css, and it works.
```css
.notion-page-content [style*='color:#EB5757']:not(.notion-text-mention-token) {
  color: var(--theme--code_inline-text) !important;
}

.notion-page-content [style*='background:rgba(135,131,120,0.15)']:not(.notion-text-mention-token) {
  background: var(--theme--code_inline) !important;
}
```
