### ISSUE TITLE
the outliner can't scroll

### ISSUE THREAD

**Issue by RichardChenW** [notion-enhancer/desktop#809]
I'm very happy that I can use outliner on my computer now. It's really a great feature.I really appreciate it!  However, I found that when there are enough content, the outliner cannot scroll, causing some information to not be displayed. I think adding  css overflow attribute should solve it, I don’t know how to deal with it?

**Comment by dragonwocky** [comment]
Last I tested, the outliner didn't work at all, so it's a pleasant surprise to see it working! To make it scrollable, add the following to your custom CSS inserts (uploaded via the tweaks extension):
```css
#enhancer--panel-content {
    max-height: 100%;
    overflow-y: scroll;
    margin: 0 !important;
    padding: 0.75rem 1rem;
}
```
