### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by lockie** [notion-enhancer/desktop#812]
**What is happening?**
The app is stuck at loading screen with the spiiner. The console says
```
7736-6593be9797866ac2.js:1 Uncaught (in promise) TypeError: Cannot read property 'getHighEntropyValues' of undefined
    at Module.o (7736-6593be9797866ac2.js:1)
    at s (mainApp-9e04b898eaf078d6.js:1)
    at notion://www.notion.so/async notion:/www.notion.so/_assets/app-45d30aa2e63ea4f4.js:1
```

**What should be happening?**
The app should work.

**Screenshots (if applicable):**
![2023-11-01-083752_2563x827_scrot](https://github.com/notion-enhancer/notion-enhancer/assets/160056/13cf4289-66fa-47ec-809d-924e2ea391c6)

**Operating system/browser name & version:**
Linux x86-64

**notion-enhancer and/or notion-repackaged version:**
notion-repackaged 2.0.18.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
The only mod I have is tray.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/116

**Comment by lexcf** [comment]
The same issue

**Comment by Antwa-sensei253** [comment]
same here after running :notion-app
```css
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
23:47:29.371 › { level: 'info', from: 'AssetCache', type: 'checkingForAppUpdate' }
23:47:29.393 › Checking for update
23:47:29.660 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/antwa/.config/notion-app/notionAssetCache-v2/latestVersion.json'
  }
}
23:47:29.662 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion/resources/app-update.yml'
23:47:29.662 › {
  level: 'info',
  from: 'autoUpdater',
  type: 'unsupportedLinuxApp',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/opt/Notion/resources/app-update.yml'",
    stack: "Error: ENOENT: no such file or directory, open '/opt/Notion/resources/app-update.yml'"
  }
}
23:47:29.669 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: { version: '23.12.0.267', hash: 'd1c29739f10fe0ac3772c6a7bd5a0c70' }
}
23:47:29.669 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersions',
  data: {
    message: 'Sync versions: assets.json path /home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets.json headers.json path /home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/headers.json'
  }
}
23:47:29.676 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: { version: '23.12.0.267' }
}
(node:151835) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
23:47:29.796 › Websocket listening on 37839...
23:47:29.800 › Set up server listeners with auth (a5cf6bc41aa5be29a56dda4bf631052e126ec133)...
(node:151835) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:151835) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
23:47:29.955 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionSameSkippingSync'
}
23:47:29.956 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest2',
  data: {
    message: 'Performing file request: /, abs path /home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/index-en-US-abda2f9eb9c392b8.html'
  }
}
23:47:30.011 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/ClientFramework-d27eb71b422934cb.js',
    url: '/_assets/ClientFramework-d27eb71b422934cb.js'
  }
}
23:47:30.012 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/8647-85f54909034f835c.js',
    url: '/_assets/8647-85f54909034f835c.js'
  }
}
23:47:30.013 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/app-cf81f3284be2a6ae.js',
    url: '/_assets/app-cf81f3284be2a6ae.js'
  }
}
23:47:30.014 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/app-5c23ade5ac874dbe.css',
    url: '/_assets/app-5c23ade5ac874dbe.css'
  }
}
23:47:30.014 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/print.5c792172.css',
    url: '/print.5c792172.css'
  }
}
23:47:30.058 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/CoreComponents-ac260bdfca0f3958.js',
    url: '/_assets/CoreComponents-ac260bdfca0f3958.js'
  }
}
23:47:30.060 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/RecordModel-988dd25c61a1cbea.js',
    url: '/_assets/RecordModel-988dd25c61a1cbea.js'
  }
}
23:47:30.061 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/RecordStore-ab9df9ff99f73686.js',
    url: '/_assets/RecordStore-ab9df9ff99f73686.js'
  }
}
23:47:30.061 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/BlockPropertyValue-70499371ac2d2a5e.js',
    url: '/_assets/BlockPropertyValue-70499371ac2d2a5e.js'
  }
}
23:47:30.062 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/PageViewBlock-3427fc40fa01f1a3.js',
    url: '/_assets/PageViewBlock-3427fc40fa01f1a3.js'
  }
}
23:47:30.063 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/2655-bf6ba35babbea32b.js',
    url: '/_assets/2655-bf6ba35babbea32b.js'
  }
}
23:47:30.064 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/9933-e38806fb0d925333.js',
    url: '/_assets/9933-e38806fb0d925333.js'
  }
}
23:47:30.064 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/7631-0e563595a7b0d9ea.js',
    url: '/_assets/7631-0e563595a7b0d9ea.js'
  }
}
23:47:30.091 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/8848-672096762d904fce.js',
    url: '/_assets/8848-672096762d904fce.js'
  }
}
23:47:30.092 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/formulas-12f234570adde0dd.js',
    url: '/_assets/formulas-12f234570adde0dd.js'
  }
}
23:47:30.092 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/9434-f12ce57a8adb617a.js',
    url: '/_assets/9434-f12ce57a8adb617a.js'
  }
}
23:47:30.094 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/7736-58b5c001521e60d3.js',
    url: '/_assets/7736-58b5c001521e60d3.js'
  }
}
23:47:30.094 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/954-1a455139ad258ea0.js',
    url: '/_assets/954-1a455139ad258ea0.js'
  }
}
23:47:30.095 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/3456-481b333c87e0de63.js',
    url: '/_assets/3456-481b333c87e0de63.js'
  }
}
23:47:30.095 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/9385-014536864e2d6c3f.js',
    url: '/_assets/9385-014536864e2d6c3f.js'
  }
}
23:47:30.096 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/9523-6461916006637592.js',
    url: '/_assets/9523-6461916006637592.js'
  }
}
23:47:30.096 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/6914-ee39e68c78bc4ab2.js',
    url: '/_assets/6914-ee39e68c78bc4ab2.js'
  }
}
23:47:30.098 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/2748-e9a8f28136aa4ba5.js',
    url: '/_assets/2748-e9a8f28136aa4ba5.js'
  }
}
23:47:30.098 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/4890-da500fc0757287f9.js',
    url: '/_assets/4890-da500fc0757287f9.js'
  }
}
23:47:30.099 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/3538-639209055e624208.js',
    url: '/_assets/3538-639209055e624208.js'
  }
}
23:47:30.099 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/9802-ee891df3990c1a66.js',
    url: '/_assets/9802-ee891df3990c1a66.js'
  }
}
23:47:30.100 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/6435-a73ff4ea3fe84255.js',
    url: '/_assets/6435-a73ff4ea3fe84255.js'
  }
}
23:47:30.100 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/2089-eb588b4829bc2365.js',
    url: '/_assets/2089-eb588b4829bc2365.js'
  }
}
23:47:30.101 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/5672-1f0d4684f73bbeb8.js',
    url: '/_assets/5672-1f0d4684f73bbeb8.js'
  }
}
23:47:30.101 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/mainApp-46f39062d629e3e7.js',
    url: '/_assets/mainApp-46f39062d629e3e7.js'
  }
}
23:47:30.148 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/8636-56c7d07cfece7369.js',
    url: '/_assets/8636-56c7d07cfece7369.js'
  }
}
23:47:30.149 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/907-d6c413baebc12dac.js',
    url: '/_assets/907-d6c413baebc12dac.js'
  }
}
23:47:30.150 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/2979-cdb1a64f6b9ac317.js',
    url: '/_assets/2979-cdb1a64f6b9ac317.js'
  }
}
23:47:30.151 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/6188-424772709b195979.js',
    url: '/_assets/6188-424772709b195979.js'
  }
}
23:47:30.151 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/SidebarComponent-0128094ce5ce505b.js',
    url: '/_assets/SidebarComponent-0128094ce5ce505b.js'
  }
}
23:47:30.166 › { level: 'info', from: 'AssetCache', type: 'noAppUpdateAvailable2' }
23:47:30.501 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/51-3783436a3f5768d6.js',
    url: '/_assets/51-3783436a3f5768d6.js'
  }
}
23:47:30.502 › {
  level: 'info',
  from: 'AssetCache',
  type: 'performingFileRequest',
  data: {
    absolutePath: '/home/antwa/.config/notion-app/notionAssetCache-v2/23.12.0.267/assets/_assets/sentry-9986b3114b32dd51.js',
    url: '/_assets/sentry-9986b3114b32dd51.js'
  }
}
```
![image](https://github.com/notion-enhancer/notion-enhancer/assets/101470839/f4644c1c-9b20-47cd-adf8-f65daa40d455)
